In [75]:
import polars as pl   # Import the requested libraries

In [76]:
df = pl.read_csv(r"C:\Users\LENOVO\Desktop\Data Analitika\d\NYC Accidents 2020.csv",try_parse_dates = True)  # Load data

In [77]:
df.shape  # Dimensions (rows/columns)

(74881, 29)

In [78]:
df.glimpse()  # General information about column names/types/values

Rows: 74881
Columns: 29
$ CRASH DATE                    <date> 2020-08-29, 2020-08-29, 2020-08-29, 2020-08-29, 2020-08-29, 2020-08-29, 2020-08-29, 2020-08-29, 2020-08-29, 2020-08-29
$ CRASH TIME                    <time> 15:40:00, 21:00:00, 18:20:00, 00:00:00, 17:10:00, 03:29:00, 19:30:00, 00:00:00, 19:50:00, 09:20:00
$ BOROUGH                        <str> 'BRONX', 'BROOKLYN', null, 'BRONX', 'BROOKLYN', null, 'BRONX', null, 'BRONX', 'QUEENS'
$ ZIP CODE                       <i64> 10466, 11221, null, 10459, 11203, null, 10459, null, 10466, 11385
$ LATITUDE                       <f64> 40.8921, 40.6905, 40.8165, 40.82472, 40.64989, 40.68231, 40.825226, 40.80016, 40.894314, 40.70678
$ LONGITUDE                      <f64> -73.83376, -73.919914, -73.946556, -73.89296, -73.93389, -73.84495, -73.88778, -73.93538, -73.86027, -73.90888
$ LOCATION                       <str> 'POINT (-73.83376 40.8921)', 'POINT (-73.919914 40.6905)', 'POINT (-73.946556 40.8165)', 'POINT (-73.89296 40.82472)', 'POINT (-73.93389 40.64989)', 'POINT (-73.84495 40.68231)', 'POINT (-73.88778 40.825226)', 'POINT (-73.93538 40.80016)', 'POINT (-73.86027 40.894314)', 'POINT (-73.90888 40.70678)'
$ ON STREET NAME                 <str> 'PRATT AVENUE', 'BUSHWICK AVENUE', '8 AVENUE', null, null, 'WOODHAVEN BOULEVARD', 'LONGFELLOW AVENUE', '2 AVENUE', 'EAST 233 STREET', null
$ CROSS STREET NAME              <str> 'STRANG AVENUE', 'PALMETTO STREET', null, null, null, null, 'EAST 165 STREET', null, 'CARPENTER AVENUE', null
$ OFF STREET NAME                <str> null, null, null, '1047 SIMPSON STREET', '4609 SNYDER AVENUE', null, null, null, null, '565 WOODWARD AVENUE'
$ NUMBER OF PERSONS INJURED      <i64> 0, 2, 1, 0, 0, 1, 0, 0, 0, 0
$ NUMBER OF PERSONS KILLED       <i64> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ NUMBER OF PEDESTRIANS INJURED  <i64> 0, 0, 1, 0, 0, 0, 0, 0, 0, 0
$ NUMBER OF PEDESTRIANS KILLED   <i64> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ NUMBER OF CYCLIST INJURED      <i64> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ NUMBER OF CYCLIST KILLED       <i64> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ NUMBER OF MOTORIST INJURED     <i64> 0, 2, 0, 0, 0, 1, 0, 0, 0, 0
$ NUMBER OF MOTORIST KILLED      <i64> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ CONTRIBUTING FACTOR VEHICLE 1  <str> 'Passing Too Closely', 'Reaction to Uninvolved Vehicle', 'Backing Unsafely', 'Unsafe Speed', 'Failure to Yield Right-of-Way', 'Unspecified', 'Unspecified', 'Unsafe Lane Changing', 'Unsafe Speed', 'Unspecified'
$ CONTRIBUTING FACTOR VEHICLE 2  <str> 'Unspecified', 'Unspecified', null, 'Unspecified', 'Unspecified', 'Unspecified', null, 'Unspecified', 'Unspecified', null
$ CONTRIBUTING FACTOR VEHICLE 3  <str> null, null, null, 'Unspecified', null, null, null, null, 'Unspecified', null
$ CONTRIBUTING FACTOR VEHICLE 4  <str> null, null, null, 'Unspecified', null, null, null, null, null, null
$ CONTRIBUTING FACTOR VEHICLE 5  <str> null, null, null, null, null, null, null, null, null, null
$ COLLISION_ID                   <i64> 4342908, 4343555, 4343142, 4343588, 4342953, 4342721, 4343004, 4343342, 4343030, 4343040
$ VEHICLE TYPE CODE 1            <str> 'Sedan', 'Sedan', 'Station Wagon/Sport Utility Vehicle', 'Station Wagon/Sport Utility Vehicle', 'Sedan', 'Station Wagon/Sport Utility Vehicle', 'Station Wagon/Sport Utility Vehicle', 'Station Wagon/Sport Utility Vehicle', 'Sedan', 'Sedan'
$ VEHICLE TYPE CODE 2            <str> 'Station Wagon/Sport Utility Vehicle', 'Sedan', null, 'Station Wagon/Sport Utility Vehicle', 'Sedan', null, null, null, 'Station Wagon/Sport Utility Vehicle', null
$ VEHICLE TYPE CODE 3            <str> null, null, null, 'Sedan', null, null, null, null, 'Sedan', null
$ VEHICLE TYPE CODE 4            <str> null, null, null, 'Motorcycle', null, null, null, null, null, null
$ VEHICLE TYPE CODE 5            <str> null, null, null, null, null, null, null, null, null, null

In [79]:
df.describe()  # Statistical summary (mean/median/min/max/std)

shape: (9, 30)
┌────────────┬───────────────┬───────────────┬─────────┬───┬──────────────┬──────────────┬──────────────┬──────────────┐
│ statistic  ┆ CRASH DATE    ┆ CRASH TIME    ┆ BOROUGH ┆ … ┆ VEHICLE TYPE ┆ VEHICLE TYPE ┆ VEHICLE TYPE ┆ VEHICLE TYPE │
│ ---        ┆ ---           ┆ ---           ┆ ---     ┆   ┆ CODE 2       ┆ CODE 3       ┆ CODE 4       ┆ CODE 5       │
│ str        ┆ str           ┆ str           ┆ str     ┆   ┆ ---          ┆ ---          ┆ ---          ┆ ---          │
│            ┆               ┆               ┆         ┆   ┆ str          ┆ str          ┆ str          ┆ str          │
╞════════════╪═══════════════╪═══════════════╪═════════╪═══╪══════════════╪══════════════╪══════════════╪══════════════╡
│ count      ┆ 74881         ┆ 74881         ┆ 49140   ┆ … ┆ 53641        ┆ 6425         ┆ 1771         ┆ 503          │
│ null_count ┆ 0             ┆ 0             ┆ 25741   ┆ … ┆ 21240        ┆ 68456        ┆ 73110        ┆ 74378        │
│ mean       ┆ 2020-04-16    ┆ 13:28:49.8102 ┆ null    ┆ … ┆ null         ┆ null         ┆ null         ┆ null         │
│            ┆ 12:59:45.5290 ┆ 32            ┆         ┆   ┆              ┆              ┆              ┆              │
│            ┆ 39            ┆               ┆         ┆   ┆              ┆              ┆              ┆              │
│ std        ┆ null          ┆ null          ┆ null    ┆ … ┆ null         ┆ null         ┆ null         ┆ null         │
│ min        ┆ 2020-01-01    ┆ 00:00:00      ┆ BRONX   ┆ … ┆ 18 WEELER    ┆ 3-Door       ┆ 4 dr sedan   ┆ BOX Truck    │
│ 25%        ┆ 2020-02-10    ┆ 09:30:00      ┆ null    ┆ … ┆ null         ┆ null         ┆ null         ┆ null         │
│ 50%        ┆ 2020-03-23    ┆ 14:14:00      ┆ null    ┆ … ┆ null         ┆ null         ┆ null         ┆ null         │
│ 75%        ┆ 2020-06-28    ┆ 18:00:00      ┆ null    ┆ … ┆ null         ┆ null         ┆ null         ┆ null         │
│ max        ┆ 2020-08-29    ┆ 23:59:00      ┆ STATEN  ┆ … ┆ van          ┆ van          ┆ trailor      ┆ Van          │
│            ┆               ┆               ┆ ISLAND  ┆   ┆              ┆              ┆              ┆              │
└────────────┴───────────────┴───────────────┴─────────┴───┴──────────────┴──────────────┴──────────────┴──────────────┘

In [80]:
df_duplicated = df.filter(df.is_duplicated())  # There are no duplicated rows in the dataset
df_duplicated

shape: (0, 29)
┌────────────┬────────────┬─────────┬──────────┬───┬────────────────┬────────────────┬────────────────┬────────────────┐
│ CRASH DATE ┆ CRASH TIME ┆ BOROUGH ┆ ZIP CODE ┆ … ┆ VEHICLE TYPE   ┆ VEHICLE TYPE   ┆ VEHICLE TYPE   ┆ VEHICLE TYPE   │
│ ---        ┆ ---        ┆ ---     ┆ ---      ┆   ┆ CODE 2         ┆ CODE 3         ┆ CODE 4         ┆ CODE 5         │
│ date       ┆ time       ┆ str     ┆ i64      ┆   ┆ ---            ┆ ---            ┆ ---            ┆ ---            │
│            ┆            ┆         ┆          ┆   ┆ str            ┆ str            ┆ str            ┆ str            │
╞════════════╪════════════╪═════════╪══════════╪═══╪════════════════╪════════════════╪════════════════╪════════════════╡
└────────────┴────────────┴─────────┴──────────┴───┴────────────────┴────────────────┴────────────────┴────────────────┘

In [87]:
df.null_count()  # Null value counts in each column. Columns with the most null values are related to vehicle types/contributing vehicle types to the accidents

shape: (1, 22)
┌────────────┬────────────┬─────────┬──────────┬───┬─────────────────┬──────────────┬─────────────────┬────────────────┐
│ CRASH DATE ┆ CRASH TIME ┆ BOROUGH ┆ ZIP CODE ┆ … ┆ CONTRIBUTING    ┆ COLLISION_ID ┆ VEHICLE TYPE    ┆ VEHICLE TYPE   │
│ ---        ┆ ---        ┆ ---     ┆ ---      ┆   ┆ FACTOR VEHICLE  ┆ ---          ┆ CODE 1          ┆ CODE 2         │
│ u32        ┆ u32        ┆ u32     ┆ u32      ┆   ┆ 2               ┆ u32          ┆ ---             ┆ ---            │
│            ┆            ┆         ┆          ┆   ┆ ---             ┆              ┆ u32             ┆ u32            │
│            ┆            ┆         ┆          ┆   ┆ u32             ┆              ┆                 ┆                │
╞════════════╪════════════╪═════════╪══════════╪═══╪═════════════════╪══════════════╪═════════════════╪════════════════╡
│ 0          ┆ 0          ┆ 25741   ┆ 25747    ┆ … ┆ 15596           ┆ 0            ┆ 635             ┆ 21240          │
└────────────┴────────────┴─────────┴──────────┴───┴─────────────────┴──────────────┴─────────────────┴────────────────┘

In [82]:
df = df.drop("LOCATION")  # Location column was removed because its coordinate information was duplicated by the separate Latitude and Longitude columns

In [86]:
df = df.drop(["OFF STREET NAME","CONTRIBUTING FACTOR VEHICLE 3","CONTRIBUTING FACTOR VEHICLE 4","CONTRIBUTING FACTOR VEHICLE 5","VEHICLE TYPE CODE 3","VEHICLE TYPE CODE 4","VEHICLE TYPE CODE 5"])
# Drop columns that have an excessively high number of null values (>90% empty) 
# such as "vehicle type code 3, 4, 5" and "contributing factor vehicle 3,4,5", 
# as well as "off street name" which is mostly empty (~73% null) 
# since the main "on street name" column is already available and provides sufficient location data

ColumnNotFoundError: "CONTRIBUTING FACTOR VEHICLE 3" not found

In [88]:
df = df.drop_nulls(["LATITUDE","LONGITUDE"]) # Rows with missing "LATITUDE" and "LONGITUDE" were dropped, as filling them would distort the dataset and render them useless for spatial analysis.

In [89]:
df = df.with_columns(
    pl.col(["BOROUGH","ON STREET NAME","CROSS STREET NAME"]).fill_null("Unknown"),
    pl.col(["CONTRIBUTING FACTOR VEHICLE 1","CONTRIBUTING FACTOR VEHICLE 2"]).fill_null("Unspecified"),
    pl.col(["VEHICLE TYPE CODE 1","VEHICLE TYPE CODE 2"]).fill_null("Unknown")
)
# Changed null values to "Unknown" and "Unspecified" according to the values in columns, since dropping them would affect the analysis

In [97]:
df.group_by("CRASH DATE").agg(
    pl.col("BOROUGH").count()
).sort("BOROUGH", descending = True)

shape: (242, 2)
┌────────────┬─────────┐
│ CRASH DATE ┆ BOROUGH │
│ ---        ┆ ---     │
│ date       ┆ u32     │
╞════════════╪═════════╡
│ 2020-01-18 ┆ 706     │
│ 2020-03-06 ┆ 621     │
│ 2020-02-14 ┆ 588     │
│ 2020-02-07 ┆ 555     │
│ 2020-02-27 ┆ 533     │
│ …          ┆ …       │
│ 2020-04-12 ┆ 96      │
│ 2020-04-23 ┆ 96      │
│ 2020-04-09 ┆ 95      │
│ 2020-04-19 ┆ 92      │
│ 2020-04-05 ┆ 84      │
└────────────┴─────────┘