In [2]:
import polars as pl

In [3]:
df = pl.read_csv(r"C:\Users\LENOVO\Desktop\Data Analitika\d\NYC Accidents 2020.csv",try_parse_dates = True)

In [4]:
df.glimpse()

Rows: 74881
Columns: 29
$ CRASH DATE                    <date> 2020-08-29, 2020-08-29, 2020-08-29, 2020-08-29, 2020-08-29, 2020-08-29, 2020-08-29, 2020-08-29, 2020-08-29, 2020-08-29
$ CRASH TIME                    <time> 15:40:00, 21:00:00, 18:20:00, 00:00:00, 17:10:00, 03:29:00, 19:30:00, 00:00:00, 19:50:00, 09:20:00
$ BOROUGH                        <str> 'BRONX', 'BROOKLYN', null, 'BRONX', 'BROOKLYN', null, 'BRONX', null, 'BRONX', 'QUEENS'
$ ZIP CODE                       <i64> 10466, 11221, null, 10459, 11203, null, 10459, null, 10466, 11385
$ LATITUDE                       <f64> 40.8921, 40.6905, 40.8165, 40.82472, 40.64989, 40.68231, 40.825226, 40.80016, 40.894314, 40.70678
$ LONGITUDE                      <f64> -73.83376, -73.919914, -73.946556, -73.89296, -73.93389, -73.84495, -73.88778, -73.93538, -73.86027, -73.90888
$ LOCATION                       <str> 'POINT (-73.83376 40.8921)', 'POINT (-73.919914 40.6905)', 'POINT (-73.946556 40.8165)', 'POINT (-73.89296 40.82472)', 'POINT (-73.93389 40.64989)', 'POINT (-73.84495 40.68231)', 'POINT (-73.88778 40.825226)', 'POINT (-73.93538 40.80016)', 'POINT (-73.86027 40.894314)', 'POINT (-73.90888 40.70678)'
$ ON STREET NAME                 <str> 'PRATT AVENUE', 'BUSHWICK AVENUE', '8 AVENUE', null, null, 'WOODHAVEN BOULEVARD', 'LONGFELLOW AVENUE', '2 AVENUE', 'EAST 233 STREET', null
$ CROSS STREET NAME              <str> 'STRANG AVENUE', 'PALMETTO STREET', null, null, null, null, 'EAST 165 STREET', null, 'CARPENTER AVENUE', null
$ OFF STREET NAME                <str> null, null, null, '1047 SIMPSON STREET', '4609 SNYDER AVENUE', null, null, null, null, '565 WOODWARD AVENUE'
$ NUMBER OF PERSONS INJURED      <i64> 0, 2, 1, 0, 0, 1, 0, 0, 0, 0
$ NUMBER OF PERSONS KILLED       <i64> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ NUMBER OF PEDESTRIANS INJURED  <i64> 0, 0, 1, 0, 0, 0, 0, 0, 0, 0
$ NUMBER OF PEDESTRIANS KILLED   <i64> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ NUMBER OF CYCLIST INJURED      <i64> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ NUMBER OF CYCLIST KILLED       <i64> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ NUMBER OF MOTORIST INJURED     <i64> 0, 2, 0, 0, 0, 1, 0, 0, 0, 0
$ NUMBER OF MOTORIST KILLED      <i64> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
$ CONTRIBUTING FACTOR VEHICLE 1  <str> 'Passing Too Closely', 'Reaction to Uninvolved Vehicle', 'Backing Unsafely', 'Unsafe Speed', 'Failure to Yield Right-of-Way', 'Unspecified', 'Unspecified', 'Unsafe Lane Changing', 'Unsafe Speed', 'Unspecified'
$ CONTRIBUTING FACTOR VEHICLE 2  <str> 'Unspecified', 'Unspecified', null, 'Unspecified', 'Unspecified', 'Unspecified', null, 'Unspecified', 'Unspecified', null
$ CONTRIBUTING FACTOR VEHICLE 3  <str> null, null, null, 'Unspecified', null, null, null, null, 'Unspecified', null
$ CONTRIBUTING FACTOR VEHICLE 4  <str> null, null, null, 'Unspecified', null, null, null, null, null, null
$ CONTRIBUTING FACTOR VEHICLE 5  <str> null, null, null, null, null, null, null, null, null, null
$ COLLISION_ID                   <i64> 4342908, 4343555, 4343142, 4343588, 4342953, 4342721, 4343004, 4343342, 4343030, 4343040
$ VEHICLE TYPE CODE 1            <str> 'Sedan', 'Sedan', 'Station Wagon/Sport Utility Vehicle', 'Station Wagon/Sport Utility Vehicle', 'Sedan', 'Station Wagon/Sport Utility Vehicle', 'Station Wagon/Sport Utility Vehicle', 'Station Wagon/Sport Utility Vehicle', 'Sedan', 'Sedan'
$ VEHICLE TYPE CODE 2            <str> 'Station Wagon/Sport Utility Vehicle', 'Sedan', null, 'Station Wagon/Sport Utility Vehicle', 'Sedan', null, null, null, 'Station Wagon/Sport Utility Vehicle', null
$ VEHICLE TYPE CODE 3            <str> null, null, null, 'Sedan', null, null, null, null, 'Sedan', null
$ VEHICLE TYPE CODE 4            <str> null, null, null, 'Motorcycle', null, null, null, null, null, null
$ VEHICLE TYPE CODE 5            <str> null, null, null, null, null, null, null, null, null, null

In [8]:
df.describe()

shape: (9, 30)
┌────────────┬────────────┬────────────┬─────────┬───┬────────────────┬────────────────┬───────────────┬───────────────┐
│ statistic  ┆ CRASH DATE ┆ CRASH TIME ┆ BOROUGH ┆ … ┆ VEHICLE TYPE   ┆ VEHICLE TYPE   ┆ VEHICLE TYPE  ┆ VEHICLE TYPE  │
│ ---        ┆ ---        ┆ ---        ┆ ---     ┆   ┆ CODE 2         ┆ CODE 3         ┆ CODE 4        ┆ CODE 5        │
│ str        ┆ str        ┆ str        ┆ str     ┆   ┆ ---            ┆ ---            ┆ ---           ┆ ---           │
│            ┆            ┆            ┆         ┆   ┆ str            ┆ str            ┆ str           ┆ str           │
╞════════════╪════════════╪════════════╪═════════╪═══╪════════════════╪════════════════╪═══════════════╪═══════════════╡
│ count      ┆ 74881      ┆ 74881      ┆ 49140   ┆ … ┆ 53641          ┆ 6425           ┆ 1771          ┆ 503           │
│ null_count ┆ 0          ┆ 0          ┆ 25741   ┆ … ┆ 21240          ┆ 68456          ┆ 73110         ┆ 74378         │
│ mean       ┆ null       ┆ null       ┆ null    ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ std        ┆ null       ┆ null       ┆ null    ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ min        ┆ 2020-01-01 ┆ 00:00:00   ┆ BRONX   ┆ … ┆ 18 WEELER      ┆ 3-Door         ┆ 4 dr sedan    ┆ BOX Truck     │
│ 25%        ┆ null       ┆ null       ┆ null    ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 50%        ┆ null       ┆ null       ┆ null    ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 75%        ┆ null       ┆ null       ┆ null    ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ max        ┆ 2020-08-29 ┆ 23:59:00   ┆ STATEN  ┆ … ┆ van            ┆ van            ┆ trailor       ┆ Van           │
│            ┆            ┆            ┆ ISLAND  ┆   ┆                ┆                ┆               ┆               │
└────────────┴────────────┴────────────┴─────────┴───┴────────────────┴────────────────┴───────────────┴───────────────┘

In [15]:
with pl.Config(tbl_rows=-1):
    print(df.head(50))

shape: (50, 29)
┌────────────┬────────────┬───────────┬──────────┬───┬────────────────┬────────────────┬───────────────┬───────────────┐
│ CRASH DATE ┆ CRASH TIME ┆ BOROUGH   ┆ ZIP CODE ┆ … ┆ VEHICLE TYPE   ┆ VEHICLE TYPE   ┆ VEHICLE TYPE  ┆ VEHICLE TYPE  │
│ ---        ┆ ---        ┆ ---       ┆ ---      ┆   ┆ CODE 2         ┆ CODE 3         ┆ CODE 4        ┆ CODE 5        │
│ str        ┆ str        ┆ str       ┆ i64      ┆   ┆ ---            ┆ ---            ┆ ---           ┆ ---           │
│            ┆            ┆           ┆          ┆   ┆ str            ┆ str            ┆ str           ┆ str           │
╞════════════╪════════════╪═══════════╪══════════╪═══╪════════════════╪════════════════╪═══════════════╪═══════════════╡
│ 2020-08-29 ┆ 15:40:00   ┆ BRONX     ┆ 10466    ┆ … ┆ Station        ┆ null           ┆ null          ┆ null          │
│            ┆            ┆           ┆          ┆   ┆ Wagon/Sport    ┆                ┆               ┆               │
│            ┆            ┆           ┆          ┆   ┆ Utility Ve…    ┆                ┆               ┆               │
│ 2020-08-29 ┆ 21:00:00   ┆ BROOKLYN  ┆ 11221    ┆ … ┆ Sedan          ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 18:20:00   ┆ null      ┆ null     ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 00:00:00   ┆ BRONX     ┆ 10459    ┆ … ┆ Station        ┆ Sedan          ┆ Motorcycle    ┆ null          │
│            ┆            ┆           ┆          ┆   ┆ Wagon/Sport    ┆                ┆               ┆               │
│            ┆            ┆           ┆          ┆   ┆ Utility Ve…    ┆                ┆               ┆               │
│ 2020-08-29 ┆ 17:10:00   ┆ BROOKLYN  ┆ 11203    ┆ … ┆ Sedan          ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 03:29:00   ┆ null      ┆ null     ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 19:30:00   ┆ BRONX     ┆ 10459    ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 00:00:00   ┆ null      ┆ null     ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 19:50:00   ┆ BRONX     ┆ 10466    ┆ … ┆ Station        ┆ Sedan          ┆ null          ┆ null          │
│            ┆            ┆           ┆          ┆   ┆ Wagon/Sport    ┆                ┆               ┆               │
│            ┆            ┆           ┆          ┆   ┆ Utility Ve…    ┆                ┆               ┆               │
│ 2020-08-29 ┆ 09:20:00   ┆ QUEENS    ┆ 11385    ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 00:07:00   ┆ QUEENS    ┆ 11436    ┆ … ┆ Station        ┆ Station        ┆ null          ┆ null          │
│            ┆            ┆           ┆          ┆   ┆ Wagon/Sport    ┆ Wagon/Sport    ┆               ┆               │
│            ┆            ┆           ┆          ┆   ┆ Utility Ve…    ┆ Utility Ve…    ┆               ┆               │
│ 2020-08-29 ┆ 14:00:00   ┆ QUEENS    ┆ 11433    ┆ … ┆ Station        ┆ null           ┆ null          ┆ null          │
│            ┆            ┆           ┆          ┆   ┆ Wagon/Sport    ┆                ┆               ┆               │
│            ┆            ┆           ┆          ┆   ┆ Utility Ve…    ┆                ┆               ┆               │
│ 2020-08-29 ┆ 21:33:00   ┆ BRONX     ┆ 10455    ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 22:53:00   ┆ BROOKLYN  ┆ 11249    ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 04:14:00   ┆ null      ┆ null     ┆ … ┆ Motorcycle     ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 06:35:00   ┆ null      ┆ null     ┆ … ┆ Station        ┆ null           ┆ null          ┆ null          │
│            ┆            ┆           ┆          ┆   ┆ Wagon/Sport    ┆                ┆               ┆               │
│            ┆            ┆           ┆          ┆   ┆ Utility Ve…    ┆                ┆               ┆               │
│ 2020-08-29 ┆ 13:00:00   ┆ BROOKLYN  ┆ 11206    ┆ … ┆ Station        ┆ null           ┆ null          ┆ null          │
│            ┆            ┆           ┆          ┆   ┆ Wagon/Sport    ┆                ┆               ┆               │
│            ┆            ┆           ┆          ┆   ┆ Utility Ve…    ┆                ┆               ┆               │
│ 2020-08-29 ┆ 10:30:00   ┆ QUEENS    ┆ 11385    ┆ … ┆ Sedan          ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 12:29:00   ┆ BRONX     ┆ 10453    ┆ … ┆ Station        ┆ null           ┆ null          ┆ null          │
│            ┆            ┆           ┆          ┆   ┆ Wagon/Sport    ┆                ┆               ┆               │
│            ┆            ┆           ┆          ┆   ┆ Utility Ve…    ┆                ┆               ┆               │
│ 2020-08-29 ┆ 10:35:00   ┆ BROOKLYN  ┆ 11211    ┆ … ┆ Station        ┆ null           ┆ null          ┆ null          │
│            ┆            ┆           ┆          ┆   ┆ Wagon/Sport    ┆                ┆               ┆               │
│            ┆            ┆           ┆          ┆   ┆ Utility Ve…    ┆                ┆               ┆               │
│ 2020-08-29 ┆ 13:55:00   ┆ BROOKLYN  ┆ 11231    ┆ … ┆ Sedan          ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 00:30:00   ┆ null      ┆ null     ┆ … ┆ Sedan          ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 06:30:00   ┆ null      ┆ null     ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 19:00:00   ┆ null      ┆ null     ┆ … ┆ Station        ┆ Station        ┆ null          ┆ null          │
│            ┆            ┆           ┆          ┆   ┆ Wagon/Sport    ┆ Wagon/Sport    ┆               ┆               │
│            ┆            ┆           ┆          ┆   ┆ Utility Ve…    ┆ Utility Ve…    ┆               ┆               │
│ 2020-08-29 ┆ 01:45:00   ┆ MANHATTAN ┆ 10029    ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 08:45:00   ┆ QUEENS    ┆ 11411    ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 23:19:00   ┆ BROOKLYN  ┆ 11226    ┆ … ┆ Motorbike      ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 07:10:00   ┆ null      ┆ null     ┆ … ┆ Station        ┆ null           ┆ null          ┆ null          │
│            ┆            ┆           ┆          ┆   ┆ Wagon/Sport    ┆                ┆               ┆               │
│            ┆            ┆           ┆          ┆   ┆ Utility Ve…    ┆                ┆               ┆               │
│ 2020-08-29 ┆ 00:56:00   ┆ BRONX     ┆ 10461    ┆ … ┆ Motorcycle     ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 13:20:00   ┆ null      ┆ null     ┆ … ┆ Sedan          ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 17:45:00   ┆ null      ┆ null     ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 22:11:00   ┆ BROOKLYN  ┆ 11229    ┆ … ┆ Bike           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 14:00:00   ┆ null      ┆ null     ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 16:30:00   ┆ MANHATTAN ┆ 10002    ┆ … ┆ Station        ┆ null           ┆ null          ┆ null          │
│            ┆            ┆           ┆          ┆   ┆ Wagon/Sport    ┆                ┆               ┆               │
│            ┆            ┆           ┆          ┆   ┆ Utility Ve…    ┆                ┆               ┆               │
│ 2020-08-29 ┆ 11:25:00   ┆ BROOKLYN  ┆ 11221    ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 02:20:00   ┆ null      ┆ null     ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 05:40:00   ┆ BRONX     ┆ 10458    ┆ … ┆ Sedan          ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 18:36:00   ┆ BRONX     ┆ 10459    ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 19:50:00   ┆ BRONX     ┆ 10457    ┆ … ┆ Taxi           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 17:00:00   ┆ BROOKLYN  ┆ 11214    ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 21:45:00   ┆ BROOKLYN  ┆ 11203    ┆ … ┆ Motorbike      ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 14:30:00   ┆ BRONX     ┆ 10453    ┆ … ┆ Sedan          ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 20:51:00   ┆ QUEENS    ┆ 11411    ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 17:17:00   ┆ null      ┆ null     ┆ … ┆ Sedan          ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 20:53:00   ┆ BRONX     ┆ 10456    ┆ … ┆ Station        ┆ null           ┆ null          ┆ null          │
│            ┆            ┆           ┆          ┆   ┆ Wagon/Sport    ┆                ┆               ┆               │
│            ┆            ┆           ┆          ┆   ┆ Utility Ve…    ┆                ┆               ┆               │
│ 2020-08-29 ┆ 19:34:00   ┆ MANHATTAN ┆ 10032    ┆ … ┆ Motorcycle     ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 00:00:00   ┆ BRONX     ┆ 10466    ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 15:50:00   ┆ BROOKLYN  ┆ 11226    ┆ … ┆ Sedan          ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 00:00:00   ┆ null      ┆ null     ┆ … ┆ Station        ┆ null           ┆ null          ┆ null          │
│            ┆            ┆           ┆          ┆   ┆ Wagon/Sport    ┆                ┆               ┆               │
│            ┆            ┆           ┆          ┆   ┆ Utility Ve…    ┆                ┆               ┆               │
│ 2020-08-29 ┆ 14:17:00   ┆ null      ┆ null     ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
└────────────┴────────────┴───────────┴──────────┴───┴────────────────┴────────────────┴───────────────┴───────────────┘

In [6]:
df.schema

Schema([('CRASH DATE', Date),
        ('CRASH TIME', Time),
        ('BOROUGH', String),
        ('ZIP CODE', Int64),
        ('LATITUDE', Float64),
        ('LONGITUDE', Float64),
        ('LOCATION', String),
        ('ON STREET NAME', String),
        ('CROSS STREET NAME', String),
        ('OFF STREET NAME', String),
        ('NUMBER OF PERSONS INJURED', Int64),
        ('NUMBER OF PERSONS KILLED', Int64),
        ('NUMBER OF PEDESTRIANS INJURED', Int64),
        ('NUMBER OF PEDESTRIANS KILLED', Int64),
        ('NUMBER OF CYCLIST INJURED', Int64),
        ('NUMBER OF CYCLIST KILLED', Int64),
        ('NUMBER OF MOTORIST INJURED', Int64),
        ('NUMBER OF MOTORIST KILLED', Int64),
        ('CONTRIBUTING FACTOR VEHICLE 1', String),
        ('CONTRIBUTING FACTOR VEHICLE 2', String),
        ('CONTRIBUTING FACTOR VEHICLE 3', String),
        ('CONTRIBUTING FACTOR VEHICLE 4', String),
        ('CONTRIBUTING FACTOR VEHICLE 5', String),
        ('COLLISION_ID', Int64),
        ('VEHICLE TYPE CODE 1', String),
        ('VEHICLE TYPE CODE 2', String),
        ('VEHICLE TYPE CODE 3', String),
        ('VEHICLE TYPE CODE 4', String),
        ('VEHICLE TYPE CODE 5', String)])

In [7]:
df

shape: (74_881, 29)
┌────────────┬────────────┬───────────┬──────────┬───┬────────────────┬────────────────┬───────────────┬───────────────┐
│ CRASH DATE ┆ CRASH TIME ┆ BOROUGH   ┆ ZIP CODE ┆ … ┆ VEHICLE TYPE   ┆ VEHICLE TYPE   ┆ VEHICLE TYPE  ┆ VEHICLE TYPE  │
│ ---        ┆ ---        ┆ ---       ┆ ---      ┆   ┆ CODE 2         ┆ CODE 3         ┆ CODE 4        ┆ CODE 5        │
│ date       ┆ time       ┆ str       ┆ i64      ┆   ┆ ---            ┆ ---            ┆ ---           ┆ ---           │
│            ┆            ┆           ┆          ┆   ┆ str            ┆ str            ┆ str           ┆ str           │
╞════════════╪════════════╪═══════════╪══════════╪═══╪════════════════╪════════════════╪═══════════════╪═══════════════╡
│ 2020-08-29 ┆ 15:40:00   ┆ BRONX     ┆ 10466    ┆ … ┆ Station        ┆ null           ┆ null          ┆ null          │
│            ┆            ┆           ┆          ┆   ┆ Wagon/Sport    ┆                ┆               ┆               │
│            ┆            ┆           ┆          ┆   ┆ Utility Ve…    ┆                ┆               ┆               │
│ 2020-08-29 ┆ 21:00:00   ┆ BROOKLYN  ┆ 11221    ┆ … ┆ Sedan          ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 18:20:00   ┆ null      ┆ null     ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 2020-08-29 ┆ 00:00:00   ┆ BRONX     ┆ 10459    ┆ … ┆ Station        ┆ Sedan          ┆ Motorcycle    ┆ null          │
│            ┆            ┆           ┆          ┆   ┆ Wagon/Sport    ┆                ┆               ┆               │
│            ┆            ┆           ┆          ┆   ┆ Utility Ve…    ┆                ┆               ┆               │
│ 2020-08-29 ┆ 17:10:00   ┆ BROOKLYN  ┆ 11203    ┆ … ┆ Sedan          ┆ null           ┆ null          ┆ null          │
│ …          ┆ …          ┆ …         ┆ …        ┆ … ┆ …              ┆ …              ┆ …             ┆ …             │
│ 2020-01-01 ┆ 15:13:00   ┆ BRONX     ┆ 10459    ┆ … ┆ null           ┆ null           ┆ null          ┆ null          │
│ 2020-01-01 ┆ 08:00:00   ┆ BROOKLYN  ┆ 11235    ┆ … ┆ Station        ┆ Station        ┆ null          ┆ null          │
│            ┆            ┆           ┆          ┆   ┆ Wagon/Sport    ┆ Wagon/Sport    ┆               ┆               │
│            ┆            ┆           ┆          ┆   ┆ Utility Ve…    ┆ Utility Ve…    ┆               ┆               │
│ 2020-01-01 ┆ 11:36:00   ┆ BRONX     ┆ 10461    ┆ … ┆ Pick-up Truck  ┆ null           ┆ null          ┆ null          │
│ 2020-01-01 ┆ 01:45:00   ┆ MANHATTAN ┆ 10017    ┆ … ┆ Taxi           ┆ null           ┆ null          ┆ null          │
│ 2020-01-01 ┆ 18:00:00   ┆ QUEENS    ┆ 11367    ┆ … ┆ Station        ┆ null           ┆ null          ┆ null          │
│            ┆            ┆           ┆          ┆   ┆ Wagon/Sport    ┆                ┆               ┆               │
│            ┆            ┆           ┆          ┆   ┆ Utility Ve…    ┆                ┆               ┆               │
└────────────┴────────────┴───────────┴──────────┴───┴────────────────┴────────────────┴───────────────┴───────────────┘

In [18]:
#there are no duplicated rows in the dataset
df_duplicated = df.filter(df.is_duplicated())
df_duplicated

shape: (0, 29)
┌────────────┬────────────┬─────────┬──────────┬───┬────────────────┬────────────────┬────────────────┬────────────────┐
│ CRASH DATE ┆ CRASH TIME ┆ BOROUGH ┆ ZIP CODE ┆ … ┆ VEHICLE TYPE   ┆ VEHICLE TYPE   ┆ VEHICLE TYPE   ┆ VEHICLE TYPE   │
│ ---        ┆ ---        ┆ ---     ┆ ---      ┆   ┆ CODE 2         ┆ CODE 3         ┆ CODE 4         ┆ CODE 5         │
│ date       ┆ time       ┆ str     ┆ i64      ┆   ┆ ---            ┆ ---            ┆ ---            ┆ ---            │
│            ┆            ┆         ┆          ┆   ┆ str            ┆ str            ┆ str            ┆ str            │
╞════════════╪════════════╪═════════╪══════════╪═══╪════════════════╪════════════════╪════════════════╪════════════════╡
└────────────┴────────────┴─────────┴──────────┴───┴────────────────┴────────────────┴────────────────┴────────────────┘